/*
 * Copyright 2025-2026, The Vitruvian Project. All rights reserved.
 * Distributed under the terms of the MIT License.
 */

#ifndef __VOS_ERRORS_H
#define __VOS_ERRORS_H

#include <limits.h>
#include <errno.h>

#define B_GENERAL_ERROR_BASE				INT_MIN
#define V_OS_ERROR_BASE						(B_GENERAL_ERROR_BASE + 0x1000)
#define B_OS_ERROR_BASE						(B_GENERAL_ERROR_BASE + 0x2000)
#define B_APP_ERROR_BASE					(B_GENERAL_ERROR_BASE + 0x3000)
#define B_INTERFACE_ERROR_BASE				(B_GENERAL_ERROR_BASE + 0x4000)
#define B_MEDIA_ERROR_BASE					(B_GENERAL_ERROR_BASE + 0x5000)
#define B_TRANSLATION_ERROR_BASE			(B_GENERAL_ERROR_BASE + 0x5800)
#define B_MIDI_ERROR_BASE					(B_GENERAL_ERROR_BASE + 0x6000)
#define B_STORAGE_ERROR_BASE				(B_GENERAL_ERROR_BASE + 0x7000)
#define B_POSIX_ERROR_BASE					(B_GENERAL_ERROR_BASE + 0x8000)
#define B_MAIL_ERROR_BASE					(B_GENERAL_ERROR_BASE + 0x9000)
#define B_PRINT_ERROR_BASE					(B_GENERAL_ERROR_BASE + 0xa000)
#define B_DEVICE_ERROR_BASE					(B_GENERAL_ERROR_BASE + 0xb000)

#define B_ERRORS_END						(B_GENERAL_ERROR_BASE + 0xffff)

// Where possible we map posix errors to negative errno values.
// Otherwise we define our own errors.

#define B_NO_MEMORY							-ENOMEM
#define B_IO_ERROR							-EIO
#define B_PERMISSION_DENIED					-EACCES
#define B_BAD_INDEX							(B_GENERAL_ERROR_BASE + 5)
#define B_BAD_TYPE							(B_GENERAL_ERROR_BASE + 6)
#define B_BAD_VALUE							-EINVAL
#define B_MISMATCHED_VALUES					(B_GENERAL_ERROR_BASE + 8)
#define B_NAME_NOT_FOUND					(B_GENERAL_ERROR_BASE + 9)
#define B_NAME_IN_USE						(B_GENERAL_ERROR_BASE + 10)
#define B_TIMED_OUT							(B_GENERAL_ERROR_BASE + 11)
#define B_INTERRUPTED						-EINTR
#define B_WOULD_BLOCK						-EAGAIN
#define B_CANCELED							-ECANCELED
#define B_NO_INIT							(B_GENERAL_ERROR_BASE + 14)
#define B_NOT_INITIALIZED					-EINIT
#define B_BUSY								-EBUSY
// B_NOT_ALLOWED should be eperm but since it is -1 would clash with B_ERROR
#define B_NOT_ALLOWED						(B_GENERAL_ERROR_BASE + 16)
#define B_BAD_DATA							(B_GENERAL_ERROR_BASE + 17)
#define B_DONT_DO_THAT						(B_GENERAL_ERROR_BASE + 18)

#define B_ERROR								(-1)
#define B_OK								((int)0)
#define B_NO_ERROR							((int)0)

#define B_BAD_SEM_ID						(B_OS_ERROR_BASE + 1)
#define B_NO_MORE_SEMS						(B_OS_ERROR_BASE + 2)

#define B_BAD_THREAD_ID						(B_OS_ERROR_BASE + 3)
#define B_NO_MORE_THREADS					(B_OS_ERROR_BASE + 4)
#define B_BAD_THREAD_STATE					(B_OS_ERROR_BASE + 5)
#define B_BAD_TEAM_ID						-ESRCH
#define B_NO_MORE_TEAMS						(B_OS_ERROR_BASE + 7)

#define B_BAD_PORT_ID						(B_OS_ERROR_BASE + 8)
#define B_NO_MORE_PORTS						(B_OS_ERROR_BASE + 9)

#define B_BAD_IMAGE_ID						(B_OS_ERROR_BASE + 10)
#define B_BAD_ADDRESS						-EFAULT
#define B_NOT_AN_EXECUTABLE					-ENOEXEC
#define B_MISSING_LIBRARY					(B_OS_ERROR_BASE + 13)
#define B_MISSING_SYMBOL					(B_OS_ERROR_BASE + 14)
#define B_UNKNOWN_EXECUTABLE				(B_OS_ERROR_BASE + 15)
#define B_LEGACY_EXECUTABLE					(B_OS_ERROR_BASE + 16)

#define B_DEBUGGER_ALREADY_INSTALLED		(B_OS_ERROR_BASE + 17)

#define B_BAD_REPLY							(B_APP_ERROR_BASE + 1)
#define B_DUPLICATE_REPLY					(B_APP_ERROR_BASE + 2)
#define B_MESSAGE_TO_SELF					(B_APP_ERROR_BASE + 3)
#define B_BAD_HANDLER						(B_APP_ERROR_BASE + 4)
#define B_ALREADY_RUNNING					(B_APP_ERROR_BASE + 5)
#define B_LAUNCH_FAILED						(B_APP_ERROR_BASE + 6)
#define B_AMBIGUOUS_APP_LAUNCH				(B_APP_ERROR_BASE + 7)
#define B_UNKNOWN_MIME_TYPE					(B_APP_ERROR_BASE + 8)
#define B_BAD_SCRIPT_SYNTAX					(B_APP_ERROR_BASE + 9)
#define B_LAUNCH_FAILED_NO_RESOLVE_LINK		(B_APP_ERROR_BASE + 10)
#define B_LAUNCH_FAILED_EXECUTABLE			(B_APP_ERROR_BASE + 11)
#define B_LAUNCH_FAILED_APP_NOT_FOUND		(B_APP_ERROR_BASE + 12)
#define B_LAUNCH_FAILED_APP_IN_TRASH		(B_APP_ERROR_BASE + 13)
#define B_LAUNCH_FAILED_NO_PREFERRED_APP	(B_APP_ERROR_BASE + 14)
#define B_LAUNCH_FAILED_FILES_APP_NOT_FOUND	(B_APP_ERROR_BASE + 15)
#define B_BAD_MIME_SNIFFER_RULE				(B_APP_ERROR_BASE + 16)
#define B_NOT_A_MESSAGE						(B_APP_ERROR_BASE + 17)
#define B_SHUTDOWN_CANCELLED				(B_APP_ERROR_BASE + 18)
#define B_SHUTTING_DOWN						(B_APP_ERROR_BASE + 19)

#define B_FILE_ERROR						-EBADF
#define B_FILE_NOT_FOUND					(B_STORAGE_ERROR_BASE + 2)
#define B_FILE_EXISTS						-EEXIST
#define B_ENTRY_NOT_FOUND					-ENOENT
#define B_NAME_TOO_LONG						-ENAMETOOLONG
#define B_NOT_A_DIRECTORY					-ENOTDIR
#define B_DIRECTORY_NOT_EMPTY				-ENOTEMPTY
#define B_DEVICE_FULL						-ENOSPC
#define B_READ_ONLY_DEVICE					-EROFS
#define B_IS_A_DIRECTORY					-EISDIR
#define B_NO_MORE_FDS						-EDQUOT
#define B_CROSS_DEVICE_LINK					-EXDEV
#define B_LINK_LIMIT						-ELOOP
#define B_BUSTED_PIPE						-EPIPE
#define B_UNSUPPORTED						(B_STORAGE_ERROR_BASE + 14)
#define B_PARTITION_TOO_SMALL				(B_STORAGE_ERROR_BASE + 15)
#define B_PARTIAL_READ						(B_STORAGE_ERROR_BASE + 16)
#define B_PARTIAL_WRITE						(B_STORAGE_ERROR_BASE + 17)

#define B_BUFFER_OVERFLOW					-EOVERFLOW
#define B_TOO_MANY_ARGS						-E2BIG
#define B_FILE_TOO_LARGE					-EFBIG
#define B_RESULT_NOT_REPRESENTABLE			-ERANGE
#define B_DEVICE_NOT_FOUND					-ENODEV
#define B_NOT_SUPPORTED						-EOPNOTSUPP

#define B_STREAM_NOT_FOUND					(B_MEDIA_ERROR_BASE + 1)
#define B_SERVER_NOT_FOUND					(B_MEDIA_ERROR_BASE + 2)
#define B_RESOURCE_NOT_FOUND				(B_MEDIA_ERROR_BASE + 3)
#define B_RESOURCE_UNAVAILABLE				(B_MEDIA_ERROR_BASE + 4)
#define B_BAD_SUBSCRIBER					(B_MEDIA_ERROR_BASE + 5)
#define B_SUBSCRIBER_NOT_ENTERED			(B_MEDIA_ERROR_BASE + 6)
#define B_BUFFER_NOT_AVAILABLE				(B_MEDIA_ERROR_BASE + 7)
#define B_LAST_BUFFER_ERROR					(B_MEDIA_ERROR_BASE + 8)

#define B_MEDIA_SYSTEM_FAILURE				(B_MEDIA_ERROR_BASE + 200)
#define B_MEDIA_BAD_NODE					(B_MEDIA_ERROR_BASE + 201)
#define B_MEDIA_NODE_BUSY					(B_MEDIA_ERROR_BASE + 202)
#define B_MEDIA_BAD_FORMAT					(B_MEDIA_ERROR_BASE + 203)
#define B_MEDIA_BAD_BUFFER					(B_MEDIA_ERROR_BASE + 204)
#define B_MEDIA_TOO_MANY_NODES				(B_MEDIA_ERROR_BASE + 205)
#define B_MEDIA_TOO_MANY_BUFFERS			(B_MEDIA_ERROR_BASE + 206)
#define B_MEDIA_NODE_ALREADY_EXISTS			(B_MEDIA_ERROR_BASE + 207)
#define B_MEDIA_BUFFER_ALREADY_EXISTS		(B_MEDIA_ERROR_BASE + 208)
#define B_MEDIA_CANNOT_SEEK					(B_MEDIA_ERROR_BASE + 209)
#define B_MEDIA_CANNOT_CHANGE_RUN_MODE		(B_MEDIA_ERROR_BASE + 210)
#define B_MEDIA_APP_ALREADY_REGISTERED		(B_MEDIA_ERROR_BASE + 211)
#define B_MEDIA_APP_NOT_REGISTERED			(B_MEDIA_ERROR_BASE + 212)
#define B_MEDIA_CANNOT_RECLAIM_BUFFERS		(B_MEDIA_ERROR_BASE + 213)
#define B_MEDIA_BUFFERS_NOT_RECLAIMED		(B_MEDIA_ERROR_BASE + 214)
#define B_MEDIA_TIME_SOURCE_STOPPED			(B_MEDIA_ERROR_BASE + 215)
#define B_MEDIA_TIME_SOURCE_BUSY			(B_MEDIA_ERROR_BASE + 216)
#define B_MEDIA_BAD_SOURCE					(B_MEDIA_ERROR_BASE + 217)
#define B_MEDIA_BAD_DESTINATION				(B_MEDIA_ERROR_BASE + 218)
#define B_MEDIA_ALREADY_CONNECTED			(B_MEDIA_ERROR_BASE + 219)
#define B_MEDIA_NOT_CONNECTED				(B_MEDIA_ERROR_BASE + 220)
#define B_MEDIA_BAD_CLIP_FORMAT				(B_MEDIA_ERROR_BASE + 221)
#define B_MEDIA_ADDON_FAILED				(B_MEDIA_ERROR_BASE + 222)
#define B_MEDIA_ADDON_DISABLED				(B_MEDIA_ERROR_BASE + 223)
#define B_MEDIA_CHANGE_IN_PROGRESS			(B_MEDIA_ERROR_BASE + 224)
#define B_MEDIA_STALE_CHANGE_COUNT			(B_MEDIA_ERROR_BASE + 225)
#define B_MEDIA_ADDON_RESTRICTED			(B_MEDIA_ERROR_BASE + 226)
#define B_MEDIA_NO_HANDLER					(B_MEDIA_ERROR_BASE + 227)
#define B_MEDIA_DUPLICATE_FORMAT			(B_MEDIA_ERROR_BASE + 228)
#define B_MEDIA_REALTIME_DISABLED			(B_MEDIA_ERROR_BASE + 229)
#define B_MEDIA_REALTIME_UNAVAILABLE		(B_MEDIA_ERROR_BASE + 230)

#define B_MAIL_NO_DAEMON					(B_MAIL_ERROR_BASE + 1)
#define B_MAIL_UNKNOWN_USER					(B_MAIL_ERROR_BASE + 2)
#define B_MAIL_WRONG_PASSWORD				(B_MAIL_ERROR_BASE + 3)
#define B_MAIL_UNKNOWN_HOST					(B_MAIL_ERROR_BASE + 4)
#define B_MAIL_ACCESS_ERROR					(B_MAIL_ERROR_BASE + 5)
#define B_MAIL_UNKNOWN_FIELD				(B_MAIL_ERROR_BASE + 6)
#define B_MAIL_NO_RECIPIENT					(B_MAIL_ERROR_BASE + 7)
#define B_MAIL_INVALID_MAIL					(B_MAIL_ERROR_BASE + 8)

#define B_NO_PRINT_SERVER					(B_PRINT_ERROR_BASE + 1)

#define B_DEV_INVALID_IOCTL					(B_DEVICE_ERROR_BASE + 1)
#define B_DEV_NO_MEMORY						(B_DEVICE_ERROR_BASE + 2)
#define B_DEV_BAD_DRIVE_NUM					(B_DEVICE_ERROR_BASE + 3)
#define B_DEV_NO_MEDIA						(B_DEVICE_ERROR_BASE + 4)
#define B_DEV_UNREADABLE					(B_DEVICE_ERROR_BASE + 5)
#define B_DEV_FORMAT_ERROR					(B_DEVICE_ERROR_BASE + 6)
#define B_DEV_TIMEOUT						(B_DEVICE_ERROR_BASE + 7)
#define B_DEV_RECALIBRATE_ERROR				(B_DEVICE_ERROR_BASE + 8)
#define B_DEV_SEEK_ERROR					(B_DEVICE_ERROR_BASE + 9)
#define B_DEV_ID_ERROR						(B_DEVICE_ERROR_BASE + 10)
#define B_DEV_READ_ERROR					(B_DEVICE_ERROR_BASE + 11)
#define B_DEV_WRITE_ERROR					(B_DEVICE_ERROR_BASE + 12)
#define B_DEV_NOT_READY						(B_DEVICE_ERROR_BASE + 13)
#define B_DEV_MEDIA_CHANGED					(B_DEVICE_ERROR_BASE + 14)
#define B_DEV_MEDIA_CHANGE_REQUESTED		(B_DEVICE_ERROR_BASE + 15)
#define B_DEV_RESOURCE_CONFLICT				(B_DEVICE_ERROR_BASE + 16)
#define B_DEV_CONFIGURATION_ERROR			(B_DEVICE_ERROR_BASE + 17)
#define B_DEV_DISABLED_BY_USER				(B_DEVICE_ERROR_BASE + 18)
#define B_DEV_DOOR_OPEN						(B_DEVICE_ERROR_BASE + 19)

#define B_DEV_INVALID_PIPE					(B_DEVICE_ERROR_BASE + 20)
#define B_DEV_CRC_ERROR						(B_DEVICE_ERROR_BASE + 21)
#define B_DEV_STALLED						(B_DEVICE_ERROR_BASE + 22)
#define B_DEV_BAD_PID						(B_DEVICE_ERROR_BASE + 23)
#define B_DEV_UNEXPECTED_PID				(B_DEVICE_ERROR_BASE + 24)
#define B_DEV_DATA_OVERRUN					(B_DEVICE_ERROR_BASE + 25)
#define B_DEV_DATA_UNDERRUN					(B_DEVICE_ERROR_BASE + 26)
#define B_DEV_FIFO_OVERRUN					(B_DEVICE_ERROR_BASE + 27)
#define B_DEV_FIFO_UNDERRUN					(B_DEVICE_ERROR_BASE + 28)
#define B_DEV_PENDING						(B_DEVICE_ERROR_BASE + 29)
#define B_DEV_MULTIPLE_ERRORS				(B_DEVICE_ERROR_BASE + 30)
#define B_DEV_TOO_LATE						(B_DEVICE_ERROR_BASE + 31)

#define B_TRANSLATION_BASE_ERROR			(B_TRANSLATION_ERROR_BASE + 1)
#define B_NO_TRANSLATOR						(B_TRANSLATION_ERROR_BASE + 2)
#define B_ILLEGAL_DATA						(B_TRANSLATION_ERROR_BASE + 3)

#endif // __VOS_ERRORS_H
