// Auto-generated by build/scripts/gen_fs_caps.py. Do not edit.
// Source: src/system/libroot2/fs/fs_caps.json

#ifndef _LIBROOT_FS_CAPS_USER_H
#define _LIBROOT_FS_CAPS_USER_H

#include <stdint.h>
#include <string.h>
#include <strings.h>

namespace BPrivate { namespace FsCaps {

static const uint32_t kChecksum = 0x54d3f414u;

enum {
	PSEUDO      = 1u << 0,
	PERSISTENT  = 1u << 1,
	READONLY    = 1u << 2,
	ATTR        = 1u << 3,
	QUERY       = 1u << 4,
	NODEMON     = 1u << 5
};

struct Entry {
	const char*	name;
	uint32_t	magic;
	uint32_t	flags;
	const char*	legacy_name;
};

struct Alias {
	const char*	alias;
	const char*	name;
};

static const Entry kEntries[] = {
	{ "ext2", 0x0000ef53u, 0x3au, "EXT2 File System" },
	{ "ext3", 0x0000ef53u, 0x3au, "EXT3 File System" },
	{ "ext4", 0x0000ef53u, 0x3au, "EXT4 File System" },
	{ "xfs", 0x58465342u, 0x3au, "XFS File System" },
	{ "btrfs", 0x9123683eu, 0x3au, "Btrfs File System" },
	{ "f2fs", 0xf2f52010u, 0x3au, "F2FS File System" },
	{ "jfs", 0x3153464au, 0x2au, "JFS File System" },
	{ "reiserfs", 0x52654973u, 0x2au, "ReiserFS File System" },
	{ "bcachefs", 0xca451a4eu, 0x2au, "bcachefs File System" },
	{ "nilfs2", 0x00003434u, 0x2au, "NILFS2 File System" },
	{ "zfs", 0x2fc12fc1u, 0x2au, "ZFS File System" },
	{ "ufs", 0x00011954u, 0x22u, "UFS File System" },
	{ "vfat", 0x00004d44u, 0x22u, "FAT32 File System" },
	{ "msdos", 0x00004d44u, 0x22u, "FAT File System" },
	{ "exfat", 0x2011bab0u, 0x22u, "exFAT File System" },
	{ "ntfs", 0x5346544eu, 0x2au, "NTFS File System" },
	{ "ntfs3", 0x5346544eu, 0x2au, "NTFS File System" },
	{ "fuseblk", 0x65735546u, 0x2au, "NTFS File System" },
	{ "hfs", 0x00004244u, 0x2au, "HFS File System" },
	{ "hfsplus", 0x0000482bu, 0x2au, "HFS+ File System" },
	{ "bfs", 0x42465331u, 0x3au, "Be File System" },
	{ "iso9660", 0x00009660u, 0x06u, "ISO9660 File System" },
	{ "udf", 0x15013346u, 0x02u, "UDF File System" },
	{ "squashfs", 0x73717368u, 0x0eu, "SquashFS File System" },
	{ "erofs", 0xe0f5e1e2u, 0x0eu, "EROFS File System" },
	{ "overlay", 0x794c7630u, 0x28u, "OverlayFS" },
	{ "aufs", 0x61756673u, 0x28u, "AUFS" },
	{ "nfs", 0x00006969u, 0x02u, "NFS" },
	{ "cifs", 0xff534d42u, 0x02u, "CIFS" },
	{ "fuse", 0x65735546u, 0x00u, "FUSE" },
	{ "tmpfs", 0x01021994u, 0x28u, "RAM File System" },
	{ "ramfs", 0x858458f6u, 0x28u, "RAM File System" },
	{ "proc", 0x00009fa0u, 0x05u, "" },
	{ "sysfs", 0x62656572u, 0x01u, "" },
	{ "devtmpfs", 0x00001373u, 0x01u, "" },
	{ "devpts", 0x00001cd1u, 0x01u, "" },
	{ "cgroup", 0x0027e0ebu, 0x01u, "" },
	{ "cgroup2", 0x63677270u, 0x01u, "" },
	{ "securityfs", 0x73636673u, 0x01u, "" },
	{ "selinuxfs", 0xf97cff8cu, 0x01u, "" },
	{ "pstore", 0x6165676cu, 0x01u, "" },
	{ "efivarfs", 0xde5e81e4u, 0x01u, "" },
	{ "bpf", 0xcafe4a11u, 0x01u, "" },
	{ "tracefs", 0x74726163u, 0x01u, "" },
	{ "debugfs", 0x64626720u, 0x01u, "" },
	{ "configfs", 0x62656570u, 0x01u, "" },
	{ "fusectl", 0x65735543u, 0x01u, "" },
	{ "hugetlbfs", 0x958458f6u, 0x01u, "" },
	{ "mqueue", 0x19800202u, 0x01u, "" },
	{ "autofs", 0x00000187u, 0x01u, "" },
	{ "rpc_pipefs", 0x67596969u, 0x01u, "" },
	{ "nfsd", 0x6e667364u, 0x01u, "" },
	{ "binfmt_misc", 0x42494e4du, 0x01u, "" },
	{ "nsfs", 0x6e736673u, 0x01u, "" },
	{ "pipefs", 0x50495045u, 0x01u, "" },
	{ "sockfs", 0x534f434bu, 0x01u, "" },
	{ "anon_inodefs", 0x09041934u, 0x01u, "" },
};
static const unsigned int kEntryCount = sizeof(kEntries)/sizeof(kEntries[0]);

static const Alias kAliases[] = {
	{ "fat", "vfat" },
	{ "fat32", "vfat" },
	{ "fat16", "msdos" },
	{ "ntfs-3g", "ntfs" },
	{ "overlayfs", "overlay" },
	{ "nfs4", "nfs" },
	{ "smbfs", "cifs" },
	{ 0, 0 }
};

static inline const Entry*
by_name(const char* mntType)
{
	if (mntType == 0)
		return 0;
	for (unsigned int i = 0; i < kEntryCount; i++) {
		if (strcasecmp(mntType, kEntries[i].name) == 0)
			return &kEntries[i];
	}
	for (unsigned int i = 0; kAliases[i].alias != 0; i++) {
		if (strcasecmp(mntType, kAliases[i].alias) == 0) {
			for (unsigned int j = 0; j < kEntryCount; j++) {
				if (strcmp(kEntries[j].name, kAliases[i].name) == 0)
					return &kEntries[j];
			}
		}
	}
	return 0;
}

static inline const Entry*
by_magic(uint32_t fType)
{
	for (unsigned int i = 0; i < kEntryCount; i++) {
		if (kEntries[i].magic == fType)
			return &kEntries[i];
	}
	return 0;
}

static inline bool is_pseudo(const char* mntType) {
	const Entry* e = by_name(mntType);
	return e != 0 && (e->flags & PSEUDO);
}
static inline bool is_persistent(const char* mntType) {
	const Entry* e = by_name(mntType);
	return e != 0 && (e->flags & PERSISTENT);
}
static inline bool is_readonly(const char* mntType) {
	const Entry* e = by_name(mntType);
	return e != 0 && (e->flags & READONLY);
}
static inline bool supports_node_monitor(uint32_t fType) {
	const Entry* e = by_magic(fType);
	return e != 0 && (e->flags & NODEMON);
}
static inline const char* legacy_name(const char* mntType) {
	const Entry* e = by_name(mntType);
	if (e == 0 || e->legacy_name == 0 || e->legacy_name[0] == 0)
		return mntType;
	return e->legacy_name;
}

} }

#endif
